### ISSUE TITLE
simulate various lines of lidar points

### ISSUE THREAD

**Issue by MMMHT** [XuelianCheng/LidarStereoNet#6]
As mentioned in Figure.6 in the paper, the authors conduct an experiment to show performance with various lines of lidar points(e.g. 1 lines, 8 lines, 16 lines). My question is how to sample the points to simulate the raw lidar points distribution? Do we need some formula(e.g. angle, coordinate) to calculate?

**Comment by yiranzhong** [comment]
Here is an example Matlab code for generating 16 lines of Lidar Points for KITTI dataset.

function [ color_map_lidar,color_map_lidar_16, Im_color ] = loadLidarpoints( frame_name,colorim_file, P2, Tr)

fid_Lidar = fopen(frame_name);

precision = 'float';
Data = fread(fid_Lidar,precision);

nPoints = length(Data)/4;
point_cloud_lidar = reshape(Data,4,nPoints);
point_cloud_lidar = point_cloud_lidar(1:3,:);

point_cloud_lidar = [point_cloud_lidar; ones(1,nPoints)];
fclose(fid_Lidar);

Im_color = imread(colorim_file);
img_width = size(Im_color,2);
img_height= size(Im_color,1);
lineMax = floor(length(point_cloud_lidar)/2108);

ppp = [];
for linenum = 1:3:lineMax
    ppptemp = point_cloud_lidar(:,2108*(linenum-1)+1:6:2108*linenum);
    ppp = [ppp, ppptemp];
end

UVW_Lidar_16 = P2*Tr*ppp;
UVW_Lidar = P2*Tr*point_cloud_lidar;
UV_Lidar = [];
UV_Lidar(1,:) = UVW_Lidar(1,:)./UVW_Lidar(3,:);
UV_Lidar(2,:) = UVW_Lidar(2,:)./UVW_Lidar(3,:);
ind_lidar = find(UV_Lidar(1,:)> 1 & UV_Lidar(1,:) < img_width & UV_Lidar(2,:)>1 & UV_Lidar(2,:) < img_height & UVW_Lidar(3,:) > 0 & UVW_Lidar(3,:) < 1000);
color_map_lidar = zeros(img_height,img_width);

UV_Lidar_16 = [];
UV_Lidar_16(1,:) = UVW_Lidar_16(1,:)./UVW_Lidar_16(3,:);
UV_Lidar_16(2,:) = UVW_Lidar_16(2,:)./UVW_Lidar_16(3,:);
ind_lidar_16 = find(UV_Lidar_16(1,:)> 1 & UV_Lidar_16(1,:) < img_width & UV_Lidar_16(2,:)>1 & UV_Lidar_16(2,:) < img_height & UVW_Lidar_16(3,:) > 0 & UVW_Lidar_16(3,:) < 1000);
color_map_lidar_16 = zeros(img_height,img_width);

%%
for i = 1:length(ind_lidar)
    position(i,:) = UV_Lidar(:,ind_lidar(i));
    u = round(position(i,2));
    v = round(position(i,1));
    color_map_lidar(u,v) = UVW_Lidar(3,ind_lidar(i));
end

for i = 1:length(ind_lidar_16)
    position_16(i,:) = UV_Lidar_16(:,ind_lidar_16(i));
    u = round(position_16(i,2));
    v = round(position_16(i,1));
    color_map_lidar_16(u,v) = UVW_Lidar_16(3,ind_lidar_16(i));
end


end

**Comment by CHXAdmin** [comment]
"May I ask which sequences from the SYNTHIA dataset were used for training and testing in your article? I would like to compare my method with yours using this dataset."

**Comment by CHXAdmin** [comment]
> 

"May I ask which sequences from the SYNTHIA dataset were used for training and testing in your article? I would like to compare my method with yours using this dataset."
